### ---------------------------------------------------------------------------------
### Original Author: [replace with your email address]
### Usage :          [replace with an overview of the playbook]
### Input Variables: [provide the list of variables used]
### ---------------------------------------------------------------------------------

---

- hosts: [replace this with the hostname from the hosts file, the block name from the hosts file, or the parameter name]
  gather_facts: no
  remote_user: [replace this with the target application account]
    
  tasks:
     - name: Running a database query...
       shell: |
            . /home/user1/.profile 2>/dev/null 1>/dev/null
            sqlplus  -s "{{ oracle_username }}/{{ orcale_password }}@{{ oracle_host }}:{{ oracle_port }}/{{ oracle_servicename }}" << eof             
            select * from DUAL;
            exit;
            eof     
      register: output  

    - debug: var=output.stdout_lines